version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\muesli\beehive

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

install:
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - git submodule update --init

build_script:
    - go build
    - go test -v
